package com.pilot;

/**
 * Data structure of the results generated by a race
 */
public class RaceResult {

	/** The time. */
	private double time;

	/** The points. */
	private int points;

	/** The dropout. */
	private boolean dropout;

	/**
	 * Instantiates a new race result.
	 */
	public RaceResult() {
		this.dropout = false;
		time = 0;
	}

	/**
	 * Gets the time.
	 *
	 * @return the time
	 */
	public double getTime() {
		return time;
	}

	/**
	 * Sets the time.
	 *
	 * @param time the new time
	 */
	public void setTime(double time) {
		this.time = time;
	}

	/**
	 * Gets the points.
	 *
	 * @return the points
	 */
	public int getPoints() {
		return points;
	}

	/**
	 * Sets the points.
	 *
	 * @param points the new points
	 */
	public void setPoints(int points) {
		this.points = points;
	}

	/**
	 * Checks if is dropout.
	 *
	 * @return true, if is dropout
	 */
	public boolean isDropout() {
		return dropout;
	}

	/**
	 * Sets the dropout.
	 *
	 * @param dropout the new dropout
	 */
	public void setDropout(boolean dropout) {
		this.dropout = dropout;
	}

}
